# Stack pour stack web Coup D'Oeil de MilleGrilles
version: '3.7'

services:

  # Application Meteor pour Coup D'Oeil
  coupdoeilmeteor:
    image: registry.maple.mdugre.info:5000/coupdoeil_meteor.x86_64:v0.9.0
    hostname: coupdoeilmeteor.maple.millegrilles.mdugre.info
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.labels.netzone.private == true
          - node.labels.millegrilles.coupdoeil == true
      resources:
       limits:
          cpus: "1.00"
          memory: 1G
      restart_policy:
        condition: any
        delay: 30s
    ports:
      - "3001:3000"
    environment:
      MONGO_URL: mongodb://coupdoeilmeteor:higCYUD096aQUI67@mongo/mg-maple?ssl=true
      MONGO_OPLOG_URL: mongodb://coupdoeilmeteor:higCYUD096aQUI67@mongo/local?ssl=true&authSource=admin
    networks:
      - mg_net

networks:
  mg_net:
    external: true
    name: mg_net
