# Stack pour stack web Coup D'Oeil de MilleGrilles
version: '3.7'

services:

  # Application Meteor pour Coup D'Oeil
  coupdoeilmeteor:
    image:  registry.maple.mdugre.info:5000/coupdoeil_meteor.x86_64:v1.2-pivoine.1
    hostname: coupdoeilmeteor.maple.millegrilles.mdugre.info
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.labels.netzone.private == true
          - node.labels.millegrilles.coupdoeil == true
      resources:
       limits:
          cpus: "1.00"
          memory: 512M
      restart_policy:
        condition: any
        delay: 30s
    ports:
      - "3001:3000"
    environment:
      MG_NOM_MILLEGRILLE: pivoine
      MONGO_URL: mongodb://coupdoeilmeteor:higCYUD096aQUI67@mongo/mg-pivoine?ssl=true
      MONGO_OPLOG_URL: mongodb://coupdoeilmeteor:higCYUD096aQUI67@mongo/local?ssl=true&authSource=admin
      MG_MQ_HOST: mq
      MG_MQ_PORT: 5672
      MG_MQ_USER: coupdoeil
      MG_MQ_PASSWORD: gLOUj3xLAj82
      MG_MQ_PROTOCOL: amqp
    networks:
      - mg_net

  # Proxy avec nginx
  coupdoeilnginx:
    image: registry.maple.mdugre.info:5000/mg_nginx.x86_64:v1.1-pivoine.1-pivoine
    hostname: www.pivoine.millegrilles.mdugre.info
    volumes:
      - /usr/share/nginx/pivoine.millegrilles/conf.d:/etc/nginx/conf.d
      - /usr/share/nginx/pivoine.millegrilles/html:/etc/nginx/html
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.labels.netzone.public == true
      resources:
        limits:
          cpus: "1.00"
          memory: 192M
      restart_policy:
        condition: any
        delay: 30s
    ports:
     - "30080:80"
     - "30443:443"
    networks:
      - mg_net
    secrets:
      - ssl.pivoine.millegrilles.cert
      - ssl.pivoine.millegrilles.key

networks:
  mg_net:
    external: true
    name: mg_net

secrets:
  ssl.pivoine.millegrilles.cert:
    external: true
    name: ssl.pivoine.millegrilles.fullchain.20181226
  ssl.pivoine.millegrilles.key:
    external: true
    name: ssl.pivoine.millegrilles.privkey.20181226

