FROM nginx:1.17
MAINTAINER Mathieu Dugre <mail@mdugre.info>

# ENV APP_SOURCE_DIR=/opt/nginx/src
# ENV APP_BUNDLE_DIR=/opt/nginx/dist

# WORKDIR $APP_BUNDLE_DIR

# COPY . $APP_SOURCE_DIR

# EXPOSE 80
# EXPOSE 443

VOLUME /etc/nginx/conf.d
# VOLUME /usr/share/nginx/html

# RUN $APP_SOURCE_DIR/scripts/setup.sh && \
#     rm -rf $APP_SOURCE_DIR

# CMD ["/opt/nginx/dist/run.sh"]
